export const IMAGE_CREATE_REQUEST = 'IMAGE_CREATE_REQUEST'
export const IMAGE_CREATE_SUCCESS = 'IMAGE_CREATE_SUCCESS'
export const IMAGE_CREATE_FAIL = 'IMAGE_CREATE_FAIL'

export const IMAGE_GET_REQUEST = 'IMAGE_GET_REQUEST'
export const IMAGE_GET_SUCCESS = 'IMAGE_GET_SUCCESS'
export const IMAGE_GET_FAIL = 'IMAGE_GET_FAIL'

export const IMAGE_EDIT_REQUEST = 'IMAGE_EDIT_REQUEST'
export const IMAGE_EDIT_SUCCESS = 'IMAGE_EDIT_SUCCESS'
export const IMAGE_EDIT_FAIL = 'IMAGE_EDIT_FAIL'

export const IMAGE_UPDATE_REQUEST = 'IMAGE_UPDATE_REQUEST'
export const IMAGE_UPDATE_SUCCESS = 'IMAGE_UPDATE_SUCCESS'
export const IMAGE_UPDATE_FAIL = 'IMAGE_UPDATE_FAIL'



